kafka:
  orders:
    bootstrapServers: 127.0.0.1:9092
    topic: orders-topic
    groupId: orders-integrationTest
    offset: earliest
  reservations:
    bootstrapServers: 127.0.0.1:9092
    topic: reservations-topic
    groupId: reservations-integrationTest
    offset: earliest
  payments:
    bootstrapServers: 127.0.0.1:9092
    topic: payments-topic
    groupId: payments-integrationTest
    offset: earliest